import { AppState } from "./IAuth";

// ─── Auth stages ──────────────────────────────────────────────────────────────

/** The ordered authentication stages attempted by AuthPipeline.run(). */
export enum AuthStage {
  /** Cookie-based login using a saved AppState JSON array. */
  APPSTATE       = "appstate",
  /** Full credential login using email + password — generates a fresh AppState. */
  EMAIL_PASSWORD = "email-password",
}

// ─── Failure taxonomy ─────────────────────────────────────────────────────────

/**
 * Structured reason for an authentication stage failure.
 * Each value maps to a distinct remediation path.
 */
export enum AuthFailureReason {
  /** AppState cookies are missing from env/file/session — nothing to try. */
  APPSTATE_MISSING         = "appstate-missing",
  /** AppState cookies are present but Facebook rejected them as expired. */
  APPSTATE_EXPIRED         = "appstate-expired",
  /** AppState data is present but cannot be parsed (invalid JSON / not an array). */
  APPSTATE_CORRUPTED       = "appstate-corrupted",
  /** Email or password is not configured in environment variables. */
  CREDENTIAL_MISSING       = "credential-missing",
  /** Email or password was incorrect. */
  CREDENTIAL_INVALID       = "credential-invalid",
  /** Facebook requires solving a checkpoint before this session can continue. */
  CHECKPOINT               = "checkpoint",
  /** Facebook requires a two-factor verification code. */
  TWO_FACTOR_AUTH          = "two-factor-auth",
  /** The account has been suspended, restricted, or permanently disabled. */
  ACCOUNT_RESTRICTED       = "account-restricted",
  /** A transient network error (DNS, TCP, timeout) prevented the login attempt. */
  NETWORK_FAILURE          = "network-failure",
  /** Facebook returned a temporary server error (e.g. error code 1357031). */
  FACEBOOK_TEMPORARY_ERROR = "facebook-temporary-error",
  /** Reason could not be determined from the error message. */
  UNKNOWN                  = "unknown",
}

// ─── Per-stage result ─────────────────────────────────────────────────────────

/** Result of a single authentication stage attempt. */
export interface AuthStageAttempt {
  /** Which stage was attempted. */
  stage: AuthStage;
  /** Whether this stage succeeded. */
  success: boolean;
  /** Structured failure reason (only set on failure). */
  failureReason?: AuthFailureReason;
  /** Raw error message from the provider or the underlying library. */
  errorMessage?: string;
  /** Wall-clock duration of this stage in milliseconds. */
  durationMs: number;
}

// ─── Pipeline result ──────────────────────────────────────────────────────────

/**
 * Aggregated result from AuthPipeline.run().
 * Covers startup and reconnect flows.
 */
export interface AuthPipelineResult {
  /** Whether any stage succeeded. */
  success: boolean;
  /** Account identifier passed to the pipeline. */
  accountId: string;
  /**
   * Which stage ultimately succeeded.
   * Absent when all stages failed.
   */
  stageUsed?: AuthStage;
  /**
   * Ordered record of every stage that was attempted.
   * Always contains at least one entry (the AppState stage).
   */
  stages: AuthStageAttempt[];
  /**
   * The AppState that will be used for the transport connection.
   * Present only on success.
   */
  freshAppState?: AppState;
  /**
   * True when the AppState was generated by an email/password login
   * (i.e. it is a net-new set of cookies, not restored from env/session).
   */
  freshAppStateGenerated: boolean;
  /**
   * True when the session was successfully persisted to the store after login.
   * A false value does NOT mean the login failed — the bot can still run,
   * but the next reconnect will have to re-authenticate from scratch.
   */
  sessionSaved: boolean;
  /** Aggregated human-readable error when success is false. */
  errorMessage?: string;
}
